language: "en"

electron_project_path: "electron"

wake_words:
  - "sparkle"
  - "hey sparkle"
  
commands:
  "open steam":
    program: "D:\\Steam\\Steam.exe"
    expression: "happy"
    speak: "Sure, have a good time with games"
  "open genshin":
    program: "D:\\HoYoPlay\\games\\Genshin Impact game\\GenshinImpact.exe"
    expression: "sad"
    speak: "Why you need this game?"
  "hello":
    expression: "happy"
    speak: "Hello, darling!"
  "play":
    motion: "hammer"
    speak: "Bam-bam!"
  "chill":
    "motion": "start"
    "speak": "Yes, master?"

sensitivity:
  vad_threshold: 0.01

vosk:
  model_path: "models/vosk-model-en-us-0.22"