language: "en"

wake_words:
  - "hanabi"
  - "cutie"
  
commands:
  "open steam":
    program: "D:\\Steam\\Steam.exe"
    args: []
  "open genshin":
    program: "D:\\HoYoPlay\\games\\Genshin Impact game\\GenshinImpact.exe"
    args: []

avatar_actions:
  "hi":
    expression: "happy"
    speak: "Hello, darling!"
  "chill":
    motion: "idle"
    speak: "Have a nice day"
  "play":
    motion: "hammer"
    speak: "Bam-bam!"

sensitivity:
  vad_threshold: 0.01

vosk:
  model_path: "models/vosk-model-en-us-0.22"